const towns = {
  data: [
    {
      localName: "Айтос",
      localRegion: "Бургас",
      name: "Aytos",
      region: "Burgas",
    },
    {
      localName: "Аксаково",
      localRegion: "Варна",
      name: "Aksakovo",
      region: "Varna",
    },
    {
      localName: "Алфатар",
      localRegion: "Силистра",
      name: "Alfatar",
      region: "Silistra",
    },
    {
      localName: "Антоново",
      localRegion: "Търговище",
      name: "Antonovo",
      region: "Targovishte",
    },
    {
      localName: "Априлци",
      localRegion: "Ловеч",
      name: "Apriltsi",
      region: "Lovech",
    },
    {
      localName: "Ардино",
      localRegion: "Кърджали",
      name: "Ardino",
      region: "Kardzhali",
    },
    {
      localName: "Асеновград",
      localRegion: "Пловдив",
      name: "Asenovgrad",
      region: "Plovdiv",
    },
    {
      localName: "Ахелой",
      localRegion: "Бургас",
      name: "Aheloi",
      region: "Burgas",
    },
    {
      localName: "Ахтопол",
      localRegion: "Бургас",
      name: "Ahtopol",
      region: "Burgas",
    },
    {
      localName: "Балчик",
      localRegion: "Добрич",
      name: "Balchik",
      region: "Dobrich",
    },
    {
      localName: "Банкя",
      localRegion: "София град",
      name: "Bankya",
      region: "Sofia",
    },
    {
      localName: "Банско",
      localRegion: "Благоевград",
      name: "Bansko",
      region: "Blagoevgrad",
    },
    {
      localName: "Баня",
      localRegion: "Пловдив",
      name: "Banya",
      region: "Plovdiv",
    },
    {
      localName: "Батак",
      localRegion: "Пазарджик",
      name: "Batak",
      region: "Pazardzhik",
    },
    {
      localName: "Батановци",
      localRegion: "Перник",
      name: "Batanovtsi",
      region: "Pernik",
    },
    {
      localName: "Белене",
      localRegion: "Плевен",
      name: "Belene",
      region: "Pleven",
    },
    {
      localName: "Белица",
      localRegion: "Благоевград",
      name: "Belitsa",
      region: "Blagoevgrad",
    },
    {
      localName: "Белово",
      localRegion: "Пазарджик",
      name: "Belovo",
      region: "Pazardzhik",
    },
    {
      localName: "Белоградчик",
      localRegion: "Видин",
      name: "Belogradchik",
      region: "Vidin",
    },
    {
      localName: "Белослав",
      localRegion: "Варна",
      name: "Beloslav",
      region: "Varna",
    },
    {
      localName: "Берковица",
      localRegion: "Монтана",
      name: "Berkovitsa",
      region: "Montana",
    },
    {
      localName: "Благоевград",
      localRegion: "Благоевград",
      name: "Blagoevgrad",
      region: "Blagoevgrad",
    },
    {
      localName: "Бобов дол",
      localRegion: "Кюстендил",
      name: "Bobov dol",
      region: "Kyustendil",
    },
    {
      localName: "Бобошево",
      localRegion: "Кюстендил",
      name: "Boboshevo",
      region: "Kyustendil",
    },
    {
      localName: "Божурище",
      localRegion: "Софийска",
      name: "Bozhurishte",
      region: "Sofia",
    },
    {
      localName: "Бойчиновци",
      localRegion: "Монтана",
      name: "Boichinovtsi",
      region: "Montana",
    },
    {
      localName: "Болярово",
      localRegion: "Ямбол",
      name: "Bolyarovo",
      region: "Yambol",
    },
    {
      localName: "Борово",
      localRegion: "Русе",
      name: "Borovo",
      region: "Ruse",
    },
    {
      localName: "Ботевград",
      localRegion: "Софийска",
      name: "Botevgrad",
      region: "Sofia",
    },
    {
      localName: "Брацигово",
      localRegion: "Пазарджик",
      name: "Bratsigovo",
      region: "Pazardzhik",
    },
    {
      localName: "Брегово",
      localRegion: "Видин",
      name: "Bregovo",
      region: "Vidin",
    },
    {
      localName: "Брезник",
      localRegion: "Перник",
      name: "Breznik",
      region: "Pernik",
    },
    {
      localName: "Брезово",
      localRegion: "Пловдив",
      name: "Brezovo",
      region: "Plovdiv",
    },
    {
      localName: "Брусарци",
      localRegion: "Монтана",
      name: "Brusartsi",
      region: "Montana",
    },
    {
      localName: "Бургас",
      localRegion: "Бургас",
      name: "Burgas",
      region: "Burgas",
    },
    {
      localName: "Бухово",
      localRegion: "София град",
      name: "Buhovo",
      region: "Sofia",
    },
    {
      localName: "Българово",
      localRegion: "Бургас",
      name: "Bulgarovo",
      region: "Burgas",
    },
    {
      localName: "Бяла",
      localRegion: "Варна",
      name: "Byala",
      region: "Varna",
    },
    {
      localName: "Бяла",
      localRegion: "Русе",
      name: "Byala",
      region: "Ruse",
    },
    {
      localName: "Бяла Слатина",
      localRegion: "Враца",
      name: "Byala Slatina",
      region: "Vratsa",
    },
    {
      localName: "Бяла Черква",
      localRegion: "Велико Търново",
      name: "Byala Cherkva",
      region: "Veliko Tarnovo",
    },
    {
      localName: "Варна",
      localRegion: "Варна",
      name: "Varna",
      region: "Varna",
    },
    {
      localName: "Велики Преслав",
      localRegion: "Шумен",
      name: "Veliki Preslav",
      region: "Shumen",
    },
    {
      localName: "Велико Търново",
      localRegion: "Велико Търново",
      name: "Veliko Tarnovo",
      region: "Veliko Tarnovo",
    },
    {
      localName: "Велинград",
      localRegion: "Пазарджик",
      name: "Velingrad",
      region: "Pazardzhik",
    },
    {
      localName: "Ветово",
      localRegion: "Русе",
      name: "Vetovo",
      region: "Ruse",
    },
    {
      localName: "Ветрен",
      localRegion: "Пазарджик",
      name: "Vetren",
      region: "Pazardzhik",
    },
    {
      localName: "Видин",
      localRegion: "Видин",
      name: "Vidin",
      region: "Vidin",
    },
    {
      localName: "Враца",
      localRegion: "Враца",
      name: "Vratsa",
      region: "Vratsa",
    },
    {
      localName: "Вълчедръм",
      localRegion: "Монтана",
      name: "Valchedram",
      region: "Montana",
    },
    {
      localName: "Вълчи дол",
      localRegion: "Варна",
      name: "Valchi dol",
      region: "Varna",
    },
    {
      localName: "Върбица",
      localRegion: "Шумен",
      name: "Varbitsa",
      region: "Shumen",
    },
    {
      localName: "Вършец",
      localRegion: "Монтана",
      name: "Varshets",
      region: "Montana",
    },
    {
      localName: "Габрово",
      localRegion: "Габрово",
      name: "Gabrovo",
      region: "Gabrovo",
    },
    {
      localName: "Генерал Тошево",
      localRegion: "Добрич",
      name: "General Toshevo",
      region: "Dobrich",
    },
    {
      localName: "Главиница",
      localRegion: "Силистра",
      name: "Glavinitsa",
      region: "Silistra",
    },
    {
      localName: "Глоджево",
      localRegion: "Русе",
      name: "Glodzhevo",
      region: "Ruse",
    },
    {
      localName: "Годеч",
      localRegion: "Софийска",
      name: "Godech",
      region: "Sofia",
    },
    {
      localName: "Горна Оряховица",
      localRegion: "Велико Търново",
      name: "Gorna Oryahovitsa",
      region: "Veliko Tarnovo",
    },
    {
      localName: "Гоце Делчев",
      localRegion: "Благоевград",
      name: "Gotse Delchev",
      region: "Blagoevgrad",
    },
    {
      localName: "Грамада",
      localRegion: "Видин",
      name: "Gramada",
      region: "Vidin",
    },
    {
      localName: "Гулянци",
      localRegion: "Плевен",
      name: "Gulyantsi",
      region: "Pleven",
    },
    {
      localName: "Гурково",
      localRegion: "Стара Загора",
      name: "Gurkovo",
      region: "Stara Zagora",
    },
    {
      localName: "Гълъбово",
      localRegion: "Стара Загора",
      name: "Galabovo",
      region: "Stara Zagora",
    },
    {
      localName: "Две могили",
      localRegion: "Русе",
      name: "Dve mogili",
      region: "Ruse",
    },
    {
      localName: "Дебелец",
      localRegion: "Велико Търново",
      name: "Debelets",
      region: "Veliko Tarnovo",
    },
    {
      localName: "Девин",
      localRegion: "Смолян",
      name: "Devin",
      region: "Smolyan",
    },
    {
      localName: "Девня",
      localRegion: "Варна",
      name: "Devnya",
      region: "Varna",
    },
    {
      localName: "Джебел",
      localRegion: "Кърджали",
      name: "Dzhebel",
      region: "Kardzhali",
    },
    {
      localName: "Димитровград",
      localRegion: "Хасково",
      name: "Dimitrovgrad",
      region: "Haskovo",
    },
    {
      localName: "Димово",
      localRegion: "Видин",
      name: "Dimovo",
      region: "Vidin",
    },
    {
      localName: "Добринище",
      localRegion: "Благоевград",
      name: "Dobrinishte",
      region: "Blagoevgrad",
    },
    {
      localName: "Добрич",
      localRegion: "Добрич",
      name: "Dobrich",
      region: "Dobrich",
    },
    {
      localName: "Долна баня",
      localRegion: "Софийска",
      name: "Dolna banya",
      region: "Sofia",
    },
    {
      localName: "Долна Митрополия",
      localRegion: "Плевен",
      name: "Dolna Mitropoliya",
      region: "Pleven",
    },
    {
      localName: "Долна Оряховица",
      localRegion: "Велико Търново",
      name: "Dolna Oryahovitsa",
      region: "Veliko Tarnovo",
    },
    {
      localName: "Долни Дъбник",
      localRegion: "Плевен",
      name: "Dolni Dabnik",
      region: "Pleven",
    },
    {
      localName: "Долни чифлик",
      localRegion: "Варна",
      name: "Dolni chiflik",
      region: "Varna",
    },
    {
      localName: "Доспат",
      localRegion: "Смолян",
      name: "Dospat",
      region: "Smolyan",
    },
    {
      localName: "Драгоман",
      localRegion: "Софийска",
      name: "Dragoman",
      region: "Sofia",
    },
    {
      localName: "Дряново",
      localRegion: "Габрово",
      name: "Dryanovo",
      region: "Gabrovo",
    },
    {
      localName: "Дулово",
      localRegion: "Силистра",
      name: "Dulovo",
      region: "Silistra",
    },
    {
      localName: "Дунавци",
      localRegion: "Видин",
      name: "Dunavtsi",
      region: "Vidin",
    },
    {
      localName: "Дупница",
      localRegion: "Кюстендил",
      name: "Dupnitsa",
      region: "Kyustendil",
    },
    {
      localName: "Дългопол",
      localRegion: "Варна",
      name: "Dalgopol",
      region: "Varna",
    },
    {
      localName: "Елена",
      localRegion: "Велико Търново",
      name: "Elena",
      region: "Veliko Tarnovo",
    },
    {
      localName: "Елин Пелин",
      localRegion: "Софийска",
      name: "Elin Pelin",
      region: "Sofia",
    },
    {
      localName: "Елхово",
      localRegion: "Ямбол",
      name: "Elhovo",
      region: "Yambol",
    },
    {
      localName: "Етрополе",
      localRegion: "Софийска",
      name: "Etropole",
      region: "Sofia",
    },
    {
      localName: "Завет",
      localRegion: "Разград",
      name: "Zavet",
      region: "Razgrad",
    },
    {
      localName: "Земен",
      localRegion: "Перник",
      name: "Zemen",
      region: "Pernik",
    },
    {
      localName: "Златарица",
      localRegion: "Велико Търново",
      name: "Zlataritsa",
      region: "Veliko Tarnovo",
    },
    {
      localName: "Златица",
      localRegion: "Софийска",
      name: "Zlatitsa",
      region: "Sofia",
    },
    {
      localName: "Златоград",
      localRegion: "Смолян",
      name: "Zlatograd",
      region: "Smolyan",
    },
    {
      localName: "Ивайловград",
      localRegion: "Хасково",
      name: "Ivailovgrad",
      region: "Haskovo",
    },
    {
      localName: "Игнатиево",
      localRegion: "Варна",
      name: "Ignatievo",
      region: "Varna",
    },
    {
      localName: "Искър",
      localRegion: "Плевен",
      name: "Iskar",
      region: "Pleven",
    },
    {
      localName: "Исперих",
      localRegion: "Разград",
      name: "Isperih",
      region: "Razgrad",
    },
    {
      localName: "Ихтиман",
      localRegion: "Софийска",
      name: "Ihtiman",
      region: "Sofia",
    },
    {
      localName: "Каблешково",
      localRegion: "Бургас",
      name: "Kableshkovo",
      region: "Burgas",
    },
    {
      localName: "Каварна",
      localRegion: "Добрич",
      name: "Kavarna",
      region: "Dobrich",
    },
    {
      localName: "Казанлък",
      localRegion: "Стара Загора",
      name: "Kazanlak",
      region: "Stara Zagora",
    },
    {
      localName: "Калофер",
      localRegion: "Пловдив",
      name: "Kalofer",
      region: "Plovdiv",
    },
    {
      localName: "Камено",
      localRegion: "Бургас",
      name: "Kameno",
      region: "Burgas",
    },
    {
      localName: "Каолиново",
      localRegion: "Шумен",
      name: "Kaolinovo",
      region: "Shumen",
    },
    {
      localName: "Карлово",
      localRegion: "Пловдив",
      name: "Karlovo",
      region: "Plovdiv",
    },
    {
      localName: "Карнобат",
      localRegion: "Бургас",
      name: "Karnobat",
      region: "Burgas",
    },
    {
      localName: "Каспичан",
      localRegion: "Шумен",
      name: "Kaspichan",
      region: "Shumen",
    },
    {
      localName: "Кермен",
      localRegion: "Сливен",
      name: "Kermen",
      region: "Sliven",
    },
    {
      localName: "Килифарево",
      localRegion: "Велико Търново",
      name: "Kilifarevo",
      region: "Veliko Tarnovo",
    },
    {
      localName: "Китен",
      localRegion: "Бургас",
      name: "Kiten",
      region: "Burgas",
    },
    {
      localName: "Клисура",
      localRegion: "Пловдив",
      name: "Klisura",
      region: "Plovdiv",
    },
    {
      localName: "Кнежа",
      localRegion: "Плевен",
      name: "Knezha",
      region: "Pleven",
    },
    {
      localName: "Козлодуй",
      localRegion: "Враца",
      name: "Kozlodui",
      region: "Vratsa",
    },
    {
      localName: "Койнаре",
      localRegion: "Плевен",
      name: "Koinare",
      region: "Pleven",
    },
    {
      localName: "Копривщица",
      localRegion: "Софийска",
      name: "Koprivchitsa",
      region: "Sofia",
    },
    {
      localName: "Костандово",
      localRegion: "Пазарджик",
      name: "Kostandovo",
      region: "Pazardzhik",
    },
    {
      localName: "Костенец",
      localRegion: "Софийска",
      name: "Kostenets",
      region: "Sofia",
    },
    {
      localName: "Костинброд",
      localRegion: "Софийска",
      name: "Kostinbrod",
      region: "Sofia",
    },
    {
      localName: "Котел",
      localRegion: "Сливен",
      name: "Kotel",
      region: "Sliven",
    },
    {
      localName: "Кочериново",
      localRegion: "Кюстендил",
      name: "Kocherinovo",
      region: "Kyustendil",
    },
    {
      localName: "Кресна",
      localRegion: "Благоевград",
      name: "Kresna",
      region: "Blagoevgrad",
    },
    {
      localName: "Криводол",
      localRegion: "Враца",
      name: "Krivodol",
      region: "Vratsa",
    },
    {
      localName: "Кричим",
      localRegion: "Пловдив",
      name: "Krichim",
      region: "Plovdiv",
    },
    {
      localName: "Крумовград",
      localRegion: "Кърджали",
      name: "Krumovgrad",
      region: "Kardzhali",
    },
    {
      localName: "Крън",
      localRegion: "Стара Загора",
      name: "Krun",
      region: "Stara Zagora",
    },
    {
      localName: "Кубрат",
      localRegion: "Разград",
      name: "Kubrat",
      region: "Razgrad",
    },
    {
      localName: "Куклен",
      localRegion: "Пловдив",
      name: "Kuklen",
      region: "Plovdiv",
    },
    {
      localName: "Кула",
      localRegion: "Видин",
      name: "Kula",
      region: "Vidin",
    },
    {
      localName: "Кърджали",
      localRegion: "Кърджали",
      name: "Kardzhali",
      region: "Kardzhali",
    },
    {
      localName: "Кюстендил",
      localRegion: "Кюстендил",
      name: "Kyustendil",
      region: "Kyustendil",
    },
    {
      localName: "Левски",
      localRegion: "Плевен",
      name: "Levski",
      region: "Pleven",
    },
    {
      localName: "Летница",
      localRegion: "Ловеч",
      name: "Letnitsa",
      region: "Lovech",
    },
    {
      localName: "Ловеч",
      localRegion: "Ловеч",
      name: "Lovech",
      region: "Lovech",
    },
    {
      localName: "Лозница",
      localRegion: "Разград",
      name: "Loznitsa",
      region: "Razgrad",
    },
    {
      localName: "Лом",
      localRegion: "Монтана",
      name: "Lom",
      region: "Montana",
    },
    {
      localName: "Луковит",
      localRegion: "Ловеч",
      name: "Lukovit",
      region: "Lovech",
    },
    {
      localName: "Лъки",
      localRegion: "Пловдив",
      name: "Laki",
      region: "Plovdiv",
    },
    {
      localName: "Любимец",
      localRegion: "Хасково",
      name: "Lyubimets",
      region: "Haskovo",
    },
    {
      localName: "Лясковец",
      localRegion: "Велико Търново",
      name: "Lyaskovets",
      region: "Veliko Tarnovo",
    },
    {
      localName: "Мадан",
      localRegion: "Смолян",
      name: "Madan",
      region: "Smolyan",
    },
    {
      localName: "Маджарово",
      localRegion: "Хасково",
      name: "Madzharovo",
      region: "Haskovo",
    },
    {
      localName: "Малко Търново",
      localRegion: "Бургас",
      name: "Malko Tarnovo",
      region: "Burgas",
    },
    {
      localName: "Мартен",
      localRegion: "Русе",
      name: "Marten",
      region: "Ruse",
    },
    {
      localName: "Мездра",
      localRegion: "Враца",
      name: "Mezdra",
      region: "Vratsa",
    },
    {
      localName: "Мелник",
      localRegion: "Благоевград",
      name: "Melnik",
      region: "Blagoevgrad",
    },
    {
      localName: "Меричлери",
      localRegion: "Хасково",
      name: "Merichleri",
      region: "Haskovo",
    },
    {
      localName: "Мизия",
      localRegion: "Враца",
      name: "Miziya",
      region: "Vratsa",
    },
    {
      localName: "Момин проход",
      localRegion: "Софийска",
      name: "Momin prohod",
      region: "Sofia",
    },
    {
      localName: "Момчилград",
      localRegion: "Кърджали",
      name: "Momchilgrad",
      region: "Kardzhali",
    },
    {
      localName: "Монтана",
      localRegion: "Монтана",
      name: "Montana",
      region: "Montana",
    },
    {
      localName: "Мъглиж",
      localRegion: "Стара Загора",
      name: "Maglik",
      region: "Stara Zagora",
    },
    {
      localName: "Неделино",
      localRegion: "Смолян",
      name: "Nedelino",
      region: "Smolyan",
    },
    {
      localName: "Несебър",
      localRegion: "Бургас",
      name: "Nesebar",
      region: "Burgas",
    },
    {
      localName: "Николаево",
      localRegion: "Стара Загора",
      name: "Nikolaevo",
      region: "Stara Zagora",
    },
    {
      localName: "Никопол",
      localRegion: "Плевен",
      name: "Nikopol",
      region: "Pleven",
    },
    {
      localName: "Нова Загора",
      localRegion: "Сливен",
      name: "Nova Zagora",
      region: "Sliven",
    },
    {
      localName: "Нови Искър",
      localRegion: "София град",
      name: "Novi Iskar",
      region: "Sofia",
    },
    {
      localName: "Нови пазар",
      localRegion: "Шумен",
      name: "Novi pazar",
      region: "Shumen",
    },
    {
      localName: "Обзор",
      localRegion: "Бургас",
      name: "Obzor",
      region: "Burgas",
    },
    {
      localName: "Омуртаг",
      localRegion: "Търговище",
      name: "Omurtag",
      region: "Targovishte",
    },
    {
      localName: "Опака",
      localRegion: "Търговище",
      name: "Opaka",
      region: "Targovishte",
    },
    {
      localName: "Оряхово",
      localRegion: "Враца",
      name: "Oryahovo",
      region: "Vratsa",
    },
    {
      localName: "Павел баня",
      localRegion: "Стара Загора",
      name: "Pavel banya",
      region: "Stara Zagora",
    },
    {
      localName: "Павликени",
      localRegion: "Велико Търново",
      name: "Pavlikeni",
      region: "Veliko Tarnovo",
    },
    {
      localName: "Пазарджик",
      localRegion: "Пазарджик",
      name: "Pazardzhik",
      region: "Pazardzhik",
    },
    {
      localName: "Панагюрище",
      localRegion: "Пазарджик",
      name: "Panagyurishte",
      region: "Pazardzhik",
    },
    {
      localName: "Перник",
      localRegion: "Перник",
      name: "Pernik",
      region: "Pernik",
    },
    {
      localName: "Перущица",
      localRegion: "Пловдив",
      name: "Perushtitsa",
      region: "Plovdiv",
    },
    {
      localName: "Петрич",
      localRegion: "Благоевград",
      name: "Petrich",
      region: "Blagoevgrad",
    },
    {
      localName: "Пещера",
      localRegion: "Пазарджик",
      name: "Peshtera",
      region: "Pazardzhik",
    },
    {
      localName: "Пирдоп",
      localRegion: "Софийска",
      name: "Pirdop",
      region: "Sofia",
    },
    {
      localName: "Плачковци",
      localRegion: "Габрово",
      name: "Plachkovtsi",
      region: "Gabrovo",
    },
    {
      localName: "Плевен",
      localRegion: "Плевен",
      name: "Pleven",
      region: "Pleven",
    },
    {
      localName: "Плиска",
      localRegion: "Шумен",
      name: "Pliska",
      region: "Shumen",
    },
    {
      localName: "Пловдив",
      localRegion: "Пловдив",
      name: "Plovdiv",
      region: "Plovdiv",
    },
    {
      localName: "Полски Тръмбеш",
      localRegion: "Велико Търново",
      name: "Polski Trambesh",
      region: "Veliko Tarnovo",
    },
    {
      localName: "Поморие",
      localRegion: "Бургас",
      name: "Pomorie",
      region: "Burgas",
    },
    {
      localName: "Попово",
      localRegion: "Търговище",
      name: "Popovo",
      region: "Targovishte",
    },
    {
      localName: "Пордим",
      localRegion: "Плевен",
      name: "Pordim",
      region: "Pleven",
    },
    {
      localName: "Правец",
      localRegion: "Софийска",
      name: "Pravets",
      region: "Sofia",
    },
    {
      localName: "Приморско",
      localRegion: "Бургас",
      name: "Primorsko",
      region: "Burgas",
    },
    {
      localName: "Провадия",
      localRegion: "Варна",
      name: "Provadiya",
      region: "Varna",
    },
    {
      localName: "Първомай",
      localRegion: "Пловдив",
      name: "Parvomai",
      region: "Plovdiv",
    },
    {
      localName: "Раднево",
      localRegion: "Стара Загора",
      name: "Radnevo",
      region: "Stara Zagora",
    },
    {
      localName: "Радомир",
      localRegion: "Перник",
      name: "Radomir",
      region: "Pernik",
    },
    {
      localName: "Разград",
      localRegion: "Разград",
      name: "Razgrad",
      region: "Razgrad",
    },
    {
      localName: "Разлог",
      localRegion: "Благоевград",
      name: "Razlog",
      region: "Blagoevgrad",
    },
    {
      localName: "Ракитово",
      localRegion: "Пазарджик",
      name: "Rakitovo",
      region: "Pazardzhik",
    },
    {
      localName: "Раковски",
      localRegion: "Пловдив",
      name: "Rakovski",
      region: "Plovdiv",
    },
    {
      localName: "Рила",
      localRegion: "Кюстендил",
      name: "Rila",
      region: "Kyustendil",
    },
    {
      localName: "Роман",
      localRegion: "Враца",
      name: "Roman",
      region: "Vratsa",
    },
    {
      localName: "Рудозем",
      localRegion: "Смолян",
      name: "Rudozem",
      region: "Smolyan",
    },
    {
      localName: "Русе",
      localRegion: "Русе",
      name: "Ruse",
      region: "Ruse",
    },
    {
      localName: "Садово",
      localRegion: "Пловдив",
      name: "Sadovo",
      region: "Plovdiv",
    },
    {
      localName: "Самоков",
      localRegion: "Софийска",
      name: "Samokov",
      region: "Sofia",
    },
    {
      localName: "Сандански",
      localRegion: "Благоевград",
      name: "Sandanski",
      region: "Blagoevgrad",
    },
    {
      localName: "Сапарева баня",
      localRegion: "Кюстендил",
      name: "Sapareva banya",
      region: "Kyustendil",
    },
    {
      localName: "Свети Влас",
      localRegion: "Бургас",
      name: "Sveti Vlas",
      region: "Burgas",
    },
    {
      localName: "Свиленград",
      localRegion: "Хасково",
      name: "Svilengrad",
      region: "Haskovo",
    },
    {
      localName: "Свищов",
      localRegion: "Велико Търново",
      name: "Svishtov",
      region: "Veliko Tarnovo",
    },
    {
      localName: "Своге",
      localRegion: "Софийска",
      name: "Svoge",
      region: "Sofia",
    },
    {
      localName: "Севлиево",
      localRegion: "Габрово",
      name: "Sevlievo",
      region: "Gabrovo",
    },
    {
      localName: "Сеново",
      localRegion: "Русе",
      name: "Senovo",
      region: "Ruse",
    },
    {
      localName: "Септември",
      localRegion: "Пазарджик",
      name: "Septemvri",
      region: "Pazardzhik",
    },
    {
      localName: "Силистра",
      localRegion: "Силистра",
      name: "Silistra",
      region: "Silistra",
    },
    {
      localName: "Симеоновград",
      localRegion: "Хасково",
      name: "Simeonovgrad",
      region: "Haskovo",
    },
    {
      localName: "Симитли",
      localRegion: "Благоевград",
      name: "Simitli",
      region: "Blagoevgrad",
    },
    {
      localName: "Славяново",
      localRegion: "Плевен",
      name: "Slavyanovo",
      region: "Pleven",
    },
    {
      localName: "Сливен",
      localRegion: "Сливен",
      name: "Sliven",
      region: "Sliven",
    },
    {
      localName: "Сливница",
      localRegion: "Софийска",
      name: "Slivnitsa",
      region: "Sofia",
    },
    {
      localName: "Сливо поле",
      localRegion: "Русе",
      name: "Slivo pole",
      region: "Ruse",
    },
    {
      localName: "Смолян",
      localRegion: "Смолян",
      name: "Smolyan",
      region: "Smolyan",
    },
    {
      localName: "Смядово",
      localRegion: "Шумен",
      name: "Smyalovo",
      region: "Shumen",
    },
    {
      localName: "Созопол",
      localRegion: "Бургас",
      name: "Sozopol",
      region: "Burgas",
    },
    {
      localName: "Сопот",
      localRegion: "Пловдив",
      name: "Sopot",
      region: "Plovdiv",
    },
    {
      localName: "София",
      localRegion: "София град",
      name: "Sofia",
      region: "Sofia",
    },
    {
      localName: "Средец",
      localRegion: "Бургас",
      name: "Sredets",
      region: "Burgas",
    },
    {
      localName: "Стамболийски",
      localRegion: "Пловдив",
      name: "Stamboliiski",
      region: "Plovdiv",
    },
    {
      localName: "Стара Загора",
      localRegion: "Стара Загора",
      name: "Stara Zagora",
      region: "Stara Zagora",
    },
    {
      localName: "Стражица",
      localRegion: "Велико Търново",
      name: "Strazhitsa",
      region: "Veliko Tarnovo",
    },
    {
      localName: "Стралджа",
      localRegion: "Ямбол",
      name: "Straldzha",
      region: "Yambol",
    },
    {
      localName: "Стрелча",
      localRegion: "Пазарджик",
      name: "Strelcha",
      region: "Pazardzhik",
    },
    {
      localName: "Суворово",
      localRegion: "Варна",
      name: "Suvorovo",
      region: "Varna",
    },
    {
      localName: "Сунгурларе",
      localRegion: "Бургас",
      name: "Sungulare",
      region: "Burgas",
    },
    {
      localName: "Сухиндол",
      localRegion: "Велико Търново",
      name: "Suhindol",
      region: "Veliko Tarnovo",
    },
    {
      localName: "Съединение",
      localRegion: "Пловдив",
      name: "Suedninenie",
      region: "Plovdiv",
    },
    {
      localName: "Сърница",
      localRegion: "Пазарджик",
      name: "Surnitsa",
      region: "Pazardzhik",
    },
    {
      localName: "Твърдица",
      localRegion: "Сливен",
      name: "Tvurditsa",
      region: "Sliven",
    },
    {
      localName: "Тервел",
      localRegion: "Добрич",
      name: "Tervel",
      region: "Dobrich",
    },
    {
      localName: "Тетевен",
      localRegion: "Ловеч",
      name: "Teteven",
      region: "Lovech",
    },
    {
      localName: "Тополовград",
      localRegion: "Хасково",
      name: "Topolovgrad",
      region: "Haskovo",
    },
    {
      localName: "Троян",
      localRegion: "Ловеч",
      name: "Troyan",
      region: "Lovech",
    },
    {
      localName: "Трън",
      localRegion: "Перник",
      name: "Trun",
      region: "Pernik",
    },
    {
      localName: "Тръстеник",
      localRegion: "Плевен",
      name: "Trastenik",
      region: "Pleven",
    },
    {
      localName: "Трявна",
      localRegion: "Габрово",
      name: "Tryavna",
      region: "Gabrovo",
    },
    {
      localName: "Тутракан",
      localRegion: "Силистра",
      name: "Tutrakan",
      region: "Silistra",
    },
    {
      localName: "Търговище",
      localRegion: "Търговище",
      name: "Targovishte",
      region: "Targovishte",
    },
    {
      localName: "Угърчин",
      localRegion: "Ловеч",
      name: "Ugarchin",
      region: "Lovech",
    },
    {
      localName: "Хаджидимово",
      localRegion: "Благоевград",
      name: "Hadzhidimovo",
      region: "Blagoevgrad",
    },
    {
      localName: "Харманли",
      localRegion: "Хасково",
      name: "Harmanli",
      region: "Haskovo",
    },
    {
      localName: "Хасково",
      localRegion: "Хасково",
      name: "Haskovo",
      region: "Haskovo",
    },
    {
      localName: "Хисаря",
      localRegion: "Пловдив",
      name: "Hisarya",
      region: "Plovdiv",
    },
    {
      localName: "Цар Калоян",
      localRegion: "Разград",
      name: "Tsar Kaloyan",
      region: "Razgrad",
    },
    {
      localName: "Царево",
      localRegion: "Бургас",
      name: "Tsarevo",
      region: "Burgas",
    },
    {
      localName: "Чепеларе",
      localRegion: "Смолян",
      name: "Chepelare",
      region: "Smolyan",
    },
    {
      localName: "Червен бряг",
      localRegion: "Плевен",
      name: "Cherven bryag",
      region: "Pleven",
    },
    {
      localName: "Черноморец",
      localRegion: "Бургас",
      name: "Chernomorets",
      region: "Burgas",
    },
    {
      localName: "Чипровци",
      localRegion: "Монтана",
      name: "Chiprovtsi",
      region: "Montana",
    },
    {
      localName: "Чирпан",
      localRegion: "Стара Загора",
      name: "Chirpan",
      region: "Stara Zagora",
    },
    {
      localName: "Шабла",
      localRegion: "Добрич",
      name: "Shabla",
      region: "Dobrich",
    },
    {
      localName: "Шивачево",
      localRegion: "Сливен",
      name: "Shivachevo",
      region: "Sliven",
    },
    {
      localName: "Шипка",
      localRegion: "Стара Загора",
      name: "Shipka",
      region: "Stara Zagora",
    },
    {
      localName: "Шумен",
      localRegion: "Шумен",
      name: "Shumen",
      region: "Shumen",
    },
    {
      localName: "Ябланица",
      localRegion: "Ловеч",
      name: "Yablanitsa",
      region: "Lovech",
    },
    {
      localName: "Якоруда",
      localRegion: "Благоевград",
      name: "Yakoruda",
      region: "Blagoevgrad",
    },
    {
      localName: "Ямбол",
      localRegion: "Ямбол",
      name: "Yambol",
      region: "Yambol",
    },
  ],
};

export default towns;
